"""Add stripe_account_id to User model

Revision ID: 946499a935be
Revises: 
Create Date: 2025-06-06 17:22:46.484630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946499a935be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stripe_account_id')

    # ### end Alembic commands ###
